[package]
name = "my_token"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
MyTokenCreator = "0x2fe27a8d6a04d57583172cdda79df0e9"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}